// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commits.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countCommitsByDevice = `-- name: CountCommitsByDevice :one
SELECT COUNT(*) FROM commits
WHERE device_id = ?
`

func (q *Queries) CountCommitsByDevice(ctx context.Context, deviceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommitsByDevice, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalCommits = `-- name: CountTotalCommits :one
SELECT COUNT(*) FROM commits
`

func (q *Queries) CountTotalCommits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalCommits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommit = `-- name: CreateCommit :one
INSERT INTO commits (
    id, device_id, raw_samples, timestamps, quality,
    test_frequency_passed, test_frequency_ratio,
    test_runs_passed, test_runs_total, test_runs_max_length,
    test_chi_passed, test_chi_value,
    test_variance_passed, test_variance_value
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?
)
RETURNING id, device_id, raw_samples, timestamps, quality, test_frequency_passed, test_frequency_ratio, test_runs_passed, test_runs_total, test_runs_max_length, test_chi_passed, test_chi_value, test_variance_passed, test_variance_value, created_at
`

type CreateCommitParams struct {
	ID                  string          `json:"id"`
	DeviceID            string          `json:"device_id"`
	RawSamples          []byte          `json:"raw_samples"`
	Timestamps          []byte          `json:"timestamps"`
	Quality             float64         `json:"quality"`
	TestFrequencyPassed int64           `json:"test_frequency_passed"`
	TestFrequencyRatio  sql.NullFloat64 `json:"test_frequency_ratio"`
	TestRunsPassed      int64           `json:"test_runs_passed"`
	TestRunsTotal       sql.NullInt64   `json:"test_runs_total"`
	TestRunsMaxLength   sql.NullInt64   `json:"test_runs_max_length"`
	TestChiPassed       int64           `json:"test_chi_passed"`
	TestChiValue        sql.NullFloat64 `json:"test_chi_value"`
	TestVariancePassed  int64           `json:"test_variance_passed"`
	TestVarianceValue   sql.NullFloat64 `json:"test_variance_value"`
}

func (q *Queries) CreateCommit(ctx context.Context, arg CreateCommitParams) (Commit, error) {
	row := q.db.QueryRowContext(ctx, createCommit,
		arg.ID,
		arg.DeviceID,
		arg.RawSamples,
		arg.Timestamps,
		arg.Quality,
		arg.TestFrequencyPassed,
		arg.TestFrequencyRatio,
		arg.TestRunsPassed,
		arg.TestRunsTotal,
		arg.TestRunsMaxLength,
		arg.TestChiPassed,
		arg.TestChiValue,
		arg.TestVariancePassed,
		arg.TestVarianceValue,
	)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.RawSamples,
		&i.Timestamps,
		&i.Quality,
		&i.TestFrequencyPassed,
		&i.TestFrequencyRatio,
		&i.TestRunsPassed,
		&i.TestRunsTotal,
		&i.TestRunsMaxLength,
		&i.TestChiPassed,
		&i.TestChiValue,
		&i.TestVariancePassed,
		&i.TestVarianceValue,
		&i.CreatedAt,
	)
	return i, err
}

const getAverageQualityByDevice = `-- name: GetAverageQualityByDevice :one
SELECT CAST(COALESCE(AVG(quality), 0) AS REAL) FROM commits
WHERE device_id = ?
`

func (q *Queries) GetAverageQualityByDevice(ctx context.Context, deviceID string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getAverageQualityByDevice, deviceID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCommitByID = `-- name: GetCommitByID :one
SELECT id, device_id, raw_samples, timestamps, quality, test_frequency_passed, test_frequency_ratio, test_runs_passed, test_runs_total, test_runs_max_length, test_chi_passed, test_chi_value, test_variance_passed, test_variance_value, created_at FROM commits
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCommitByID(ctx context.Context, id string) (Commit, error) {
	row := q.db.QueryRowContext(ctx, getCommitByID, id)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.RawSamples,
		&i.Timestamps,
		&i.Quality,
		&i.TestFrequencyPassed,
		&i.TestFrequencyRatio,
		&i.TestRunsPassed,
		&i.TestRunsTotal,
		&i.TestRunsMaxLength,
		&i.TestChiPassed,
		&i.TestChiValue,
		&i.TestVariancePassed,
		&i.TestVarianceValue,
		&i.CreatedAt,
	)
	return i, err
}

const getCommitsByDevice = `-- name: GetCommitsByDevice :many
SELECT id, device_id, raw_samples, timestamps, quality, test_frequency_passed, test_frequency_ratio, test_runs_passed, test_runs_total, test_runs_max_length, test_chi_passed, test_chi_value, test_variance_passed, test_variance_value, created_at FROM commits
WHERE device_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetCommitsByDeviceParams struct {
	DeviceID string `json:"device_id"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) GetCommitsByDevice(ctx context.Context, arg GetCommitsByDeviceParams) ([]Commit, error) {
	rows, err := q.db.QueryContext(ctx, getCommitsByDevice, arg.DeviceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.RawSamples,
			&i.Timestamps,
			&i.Quality,
			&i.TestFrequencyPassed,
			&i.TestFrequencyRatio,
			&i.TestRunsPassed,
			&i.TestRunsTotal,
			&i.TestRunsMaxLength,
			&i.TestChiPassed,
			&i.TestChiValue,
			&i.TestVariancePassed,
			&i.TestVarianceValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCommits = `-- name: GetRecentCommits :many
SELECT id, device_id, raw_samples, timestamps, quality, test_frequency_passed, test_frequency_ratio, test_runs_passed, test_runs_total, test_runs_max_length, test_chi_passed, test_chi_value, test_variance_passed, test_variance_value, created_at FROM commits
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetRecentCommits(ctx context.Context, limit int64) ([]Commit, error) {
	rows, err := q.db.QueryContext(ctx, getRecentCommits, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commit{}
	for rows.Next() {
		var i Commit
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.RawSamples,
			&i.Timestamps,
			&i.Quality,
			&i.TestFrequencyPassed,
			&i.TestFrequencyRatio,
			&i.TestRunsPassed,
			&i.TestRunsTotal,
			&i.TestRunsMaxLength,
			&i.TestChiPassed,
			&i.TestChiValue,
			&i.TestVariancePassed,
			&i.TestVarianceValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSamplesCount = `-- name: GetTotalSamplesCount :one
SELECT CAST(COALESCE(SUM(LENGTH(raw_samples) / 4), 0) AS INTEGER) FROM commits
`

func (q *Queries) GetTotalSamplesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSamplesCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
