// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) FROM devices
`

func (q *Queries) CountDevices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id)
VALUES (?)
RETURNING id, last_seen, total_commits, average_quality, created_at
`

func (q *Queries) CreateDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LastSeen,
		&i.TotalCommits,
		&i.AverageQuality,
		&i.CreatedAt,
	)
	return i, err
}

const getAllDevices = `-- name: GetAllDevices :many
SELECT id, last_seen, total_commits, average_quality, created_at FROM devices
ORDER BY last_seen DESC
`

func (q *Queries) GetAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.LastSeen,
			&i.TotalCommits,
			&i.AverageQuality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevice = `-- name: GetDevice :one
SELECT id, last_seen, total_commits, average_quality, created_at FROM devices
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LastSeen,
		&i.TotalCommits,
		&i.AverageQuality,
		&i.CreatedAt,
	)
	return i, err
}

const getOnlineDevices = `-- name: GetOnlineDevices :many
SELECT id, last_seen, total_commits, average_quality, created_at FROM devices
WHERE last_seen > datetime('now', '-2 minutes')
ORDER BY last_seen DESC
`

func (q *Queries) GetOnlineDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getOnlineDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.LastSeen,
			&i.TotalCommits,
			&i.AverageQuality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceStats = `-- name: UpdateDeviceStats :exec
UPDATE devices
SET last_seen = ?,
    total_commits = ?,
    average_quality = ?
WHERE id = ?
`

type UpdateDeviceStatsParams struct {
	LastSeen       sql.NullTime    `json:"last_seen"`
	TotalCommits   sql.NullInt64   `json:"total_commits"`
	AverageQuality sql.NullFloat64 `json:"average_quality"`
	ID             string          `json:"id"`
}

func (q *Queries) UpdateDeviceStats(ctx context.Context, arg UpdateDeviceStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceStats,
		arg.LastSeen,
		arg.TotalCommits,
		arg.AverageQuality,
		arg.ID,
	)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (id, last_seen, total_commits, average_quality)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    last_seen = excluded.last_seen,
    total_commits = excluded.total_commits,
    average_quality = excluded.average_quality
RETURNING id, last_seen, total_commits, average_quality, created_at
`

type UpsertDeviceParams struct {
	ID             string          `json:"id"`
	LastSeen       sql.NullTime    `json:"last_seen"`
	TotalCommits   sql.NullInt64   `json:"total_commits"`
	AverageQuality sql.NullFloat64 `json:"average_quality"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice,
		arg.ID,
		arg.LastSeen,
		arg.TotalCommits,
		arg.AverageQuality,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.LastSeen,
		&i.TotalCommits,
		&i.AverageQuality,
		&i.CreatedAt,
	)
	return i, err
}
