// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Commit struct {
	ID                  string          `json:"id"`
	DeviceID            string          `json:"device_id"`
	RawSamples          []byte          `json:"raw_samples"`
	Timestamps          []byte          `json:"timestamps"`
	Quality             float64         `json:"quality"`
	TestFrequencyPassed int64           `json:"test_frequency_passed"`
	TestFrequencyRatio  sql.NullFloat64 `json:"test_frequency_ratio"`
	TestRunsPassed      int64           `json:"test_runs_passed"`
	TestRunsTotal       sql.NullInt64   `json:"test_runs_total"`
	TestRunsMaxLength   sql.NullInt64   `json:"test_runs_max_length"`
	TestChiPassed       int64           `json:"test_chi_passed"`
	TestChiValue        sql.NullFloat64 `json:"test_chi_value"`
	TestVariancePassed  int64           `json:"test_variance_passed"`
	TestVarianceValue   sql.NullFloat64 `json:"test_variance_value"`
	CreatedAt           sql.NullTime    `json:"created_at"`
}

type Device struct {
	ID             string          `json:"id"`
	LastSeen       sql.NullTime    `json:"last_seen"`
	TotalCommits   sql.NullInt64   `json:"total_commits"`
	AverageQuality sql.NullFloat64 `json:"average_quality"`
	CreatedAt      sql.NullTime    `json:"created_at"`
}
